# Generated by Django 4.2.10 on 2024-03-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_img",
            field=models.ImageField(default="default.png", upload_to="profile_pics/"),
        ),
    ]
