# Generated by Django 4.2.10 on 2024-03-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="youtube_url",
            field=models.URLField(blank=True),
        ),
    ]
